config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "room2s#index"
  
  resources :users, only: [:show, :edit, :update]
  
  resources :relationships, only: [:create, :destroy]

  resources :room2s, only: [:index, :new, :create] do
    resources :posts, only: [:index, :create]
  end

  resources :rooms, only: [:index, :new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
  
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :room
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :room2
  belongs_to :user, optional: true
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true, uniqueness: true
  validates :followed_id, presence: true, uniqueness: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_users
  has_many :users, through: :room_users, validate: false
  has_many :messages

  validates :name, presence: true
end

app/models/room2.rb
class Room2 < ApplicationRecord
  has_many :posts
  belongs_to :user
  
  validates :name, presence: true
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :room2s
  has_many :posts

  has_many :room_users
  has_many :rooms, through: :room_users
  has_many :messages
  
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end


  with_options presence: true do
    validates :password, length: { minimum: 6 }, format: {with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i}
    validates :name
  end

  validates :introduction, length: {maximum: 150}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birthday, :introduction])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '0922'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :contributor_confirmation, only: [:edit, :update]

  def index
     @post = Post.new
     @room2 = Room2.find(params[:room2_id])
     @posts = @room2.posts.includes(:user)

     query = "SELECT * FROM rooms"
     @room2s = Room2.find_by_sql(query)
   end
 
   def create
     @room2 = Room2.find(params[:room2_id])
     @post = @room2.posts.new(post_params)
     if @post.save
       redirect_to room2_posts_path(@room2)
     else
       @posts = @room2.posts.includes(:user)
       render :index
     end
   end
 
   private
   def post_params
    params.require(:post).permit(:content, :image).merge(user_id: current_user.id)
  end

  def contributor_confirmation
    @post = Post.find(params[:id])
    unless current_user == @post.user
      redirect_to root_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/room2s_controller.rb
class Room2sController < ApplicationController
  def index
    @room2s = Room2.all
  end

  def new
    @room2 = Room2.new
  end

  def create
    @room2 = Room2.new(room2_params)
    if @room2.save
      redirect_to room2s_path
    else
      render :new
    end
  end

  private
  def room2_params
    params.require(:room2).permit(:name).merge(user_id: current_user.id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to rooms_path
    else
      render :new
    end
  end

  def destroy
    room.destroy
    redirect_to rooms_path
  end

  private
  def room_params
    params.require(:room).permit(:name, user_ids:[])
  end
end

app/controllers/uers_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_root_path, only: [:index, :create]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to current_user_path
    else
      render :edit
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  private
  def user_params
    params.require(:user).permit(:name, :birthday, :introduction)
  end

  def move_to_root_path
    @user = user.find(params[:id])
    if current_user.id == @user_id
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/room2s_helper.rb
module Room2sHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/uers_helper.rb
module UersHelper
end

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
      <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>

app/views/messages/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name, user_path(current_user) %>
  </div>
  <div class="create-room">
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>

<div class="rooms">
    <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="chat">  
    <%= render "main_chat" %>
  </div>
</div>

app/views/posts/_main_chat.html.erb
<div class="chat-header">
  <div class="left-header">
    <div class="header-title">
      <%= @room2.name %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
    </div>
  </div>
</div>

<div class="messages">
  <%= render partial: 'post', collection: @posts %>
</div>

<%= form_with model: [@room2, @post], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :content, class: 'form-message', placeholder: 'type a message' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/posts/_post.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
        <%= link_to post.user.name, user_path(post.user) %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%= l post.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= post.content %>
    </div>
      <%= image_tag post.image.variant(resize: '500x500'), class: 'message-image' if post.image.attached? %>
  </div>
</div>

app/views/posts/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name, user_path(current_user) %>
  </div>
  <div class="create-room">
    <%= link_to "チャットを作成する", new_room2_path %>
  </div>
</div>

<div class="rooms">
  <% @room2s.each do |room2| %>
    <div class="room">
      <div class="room-name">
        <%= link_to room2.name, room2_posts_path(room2) %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "posts/side_bar" %>
  </div>
  <div class="chat">  
    <%= render "posts/main_chat" %>
  </div>
</div>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/room2s/index.html.erb
<%= render "shared/header" %>

<% if user_signed_in? %>
  <div class='wrapper'>
    <div class='side-bar'>
      <%= render "posts/side_bar" %>
    </div>
  </div>
<% else %>
  <div class='main'>
    <%# 画面上部の「人生を変えるフリマアプリ」帯部分 %>
    <div class='title-contents'>
      <h2 class='service-title'>
        人生を変えるビジネス出会いアプリ
      </h2>
      <p class='service-explain'>
        ORIAPPはだれでもかんたんに熱い人と出会える
      </p>
      <p class='service-explain'>
        ビジネス出会いアプリです
      </p>
      <div class='store-btn'>
      </div>
    </div>
    <%# /画面上部の「人生を変えるフリマアプリ」帯部分  %>

    <%# FURIMAが選ばれる3つの理由部分 %>
    <div class='select-reason-contents'>
      <h2 class='title'>
        ORIAPPが選ばれる3つの理由
      </h2>
      <ul class='reason-lists'>
        <li class='list'>
          <%= image_tag "pexels-fauxels-3184418.png", class:"list-pict" %>
          <span class='reason-list-number'>1</span>
          <h3 class='reason-list-text'>
            <span class='reason-list-blue-text'>3分</span>
            で新しい出会いを
          </h3>
          <p class='reason-list-description'>
            スマホで入力するだけで簡単！
          </p>
        </li>
        <li class='list'>
          <%= image_tag "pexels-burst-374720.png", class:"list-pict" %>
          <span class='reason-list-number'>2</span>
          <h3 class='reason-list-text'>
            <span class='reason-list-blue-text'>シンプル</span>
            で使いやすい
          </h3>
          <p class='reason-list-description'>
            めんどくさい入力は必要なく、検索も購入もスムーズ！
          </p>
        </li>
        <li class='list'>
          <%= image_tag "pexels-fauxels-3182759.png", class:"list-pict" %>
          <span class='reason-list-number'>3</span>
          <h3 class='reason-list-text'>
            豊富な
            <span class='reason-list-blue-text'>ジャンル</span>
          </h3>
          <p class='reason-list-description'>
            10%でお得に出品&購入！
          </p>
        </li>
      </ul>
    </div>
    <%# /FURIMAが選ばれる3つの理由部分 %>
  <%= render "shared/footer" %>
<% end %>

app/views/room2s/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room2, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/index.html.erb
<%= render "shared/header" %>

<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/uers/show.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= gravatar_for @user %>
            <a href="http://gravatar.com/emails" target="_blank">change</a>
          </div>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_stats.html.erb
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>

  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "マイページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label :password%>
          </div>
          <div class='field-input'>
          <%= f.password_field :password, class:"field-input", id:"password", placeholder:"6文字以上の半角英数字" %>
          </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label :password_confirmation%>
          </div>
          <div class='field-input'>
          <%= f.password_field :password_confirmation, class:"field-input", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
          </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label :birthday%>
          </div>
          <div class='input-birth-wrap'>
          <%= raw sprintf(
                      f.date_select(
                        :birthday,
                        class:'select-birth',
                        id:"birth-date",
                        use_month_numbers: true,
                        prompt:'--',
                        start_year: 1930,
                        end_year: (Time.now.year - 5),
                        date_separator: '%s'),
                      "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
          </div>

        <div class="items-explain">
          <div class="weight-bold-text">
            Introduction
          </div>
          <%= f.text_area :introduction, class:"items-text", id:"item-info", placeholder:"私の名前はオリアプ太郎です" %>
        </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2><%= @user.name %></h2>
      <%= link_to "編集する", edit_user_path, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
      <% if signed_in? current_user == @user %>
      <% else%>
        <%= link_to "メッセージを送る", new_room_path, class: 'btn'%>
      <% end %>
      <div id="follow_form">
        <% if signed_in? current_user == @user %>
          <% if current_user.following?(@user) %>
            <%= render 'unfollow' %>
          <% else %>
            <%= render 'follow' %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: @user, local: true do |f|%>

        <div class='field'>
          <div class="stats">
            <%= render 'users/stats' %>
          </div>
        </div>

        <div class='field'>
          <div class='field-label'>
            <%= f.label :Birthday %><%= @user.birthday %>
          </div>
        </div>

      <div class="field">
        <div class="field-label">
          <%= f.label :Introduction %> <%= @user.introduction %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<%= render "shared/header" %>

<div class="row">
  <section class="stats">
    <%= render 'users/stats' %>
    <% if @users.any? %>
      <div class="user_avatars">
        <% @users.each do |user| %>
          <%= link_to user.name, user_path(user.id) %>
        <% end %>
      </div>
    <% end %>
  </section>
  <div class='account-page' id='account-page'>
    <div class='account-page__inner--left account-page__header'>
      <%= link_to "戻る", :back, class: 'btn'%>
    </div>
  </div>
</div>